/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hostname_resolver;

import org.junit.Test;
import static org.junit.Assert.*;

public class Canary {
    @Test 
    public void testCanary() {
        assertTrue(true);
    }
}
